selected_features:
- year_days_passed
- year_days_left
- month_days_passed
- month_first_day
- month_length
- last_friday
- sunrise_dusk
- business_days_in_month
- non_business_days_in_month
- close_gld_vol5d
- close_spy_vol5d
- close_gdaxi_vol5d
- high_ief_high_vol5d
- high_spy_high_vol5d
- low_bnd_low_vol5d
- low_gld_low_vol5d
- low_spy_low_vol5d
- low_gdaxi_low_vol5d
- close_bnd_gld_corr10d
- close_bnd_gld_corr30d
- close_ief_gld_corr10d
- close_ief_gld_corr30d
- close_spy_gld_corr10d
- close_spy_gld_corr30d
- close_gdaxi_gld_corr30d
- close_bnd_spy_corr10d
- close_bnd_spy_corr30d
- close_ief_spy_corr10d
- close_ief_spy_corr30d
- close_gdaxi_spy_corr10d
- close_gdaxi_spy_corr30d
- close_bnd_gdaxi_corr10d
- close_bnd_gdaxi_corr30d
- close_ief_gdaxi_corr10d
- close_ief_gdaxi_corr30d
- close_bnd_ief_corr10d
- close_bnd_ief_corr30d
threshold: 0.14214214214214213
xgb_classifier_params:
  colsample_bytree: 0.8562910234445663
  gamma: 0.0671463942480997
  learning_rate: 0.08180051582631245
  max_depth: 8
  min_child_weight: 6
  n_estimators: 1273
  reg_alpha: 0.080528660919556
  reg_lambda: 0.03737342034779486
  subsample: 0.8496870285851796
