selected_features:
- low_gld open_spy_day20
- high_gld high_bnd_day7
- volume_ief volume_gld_day3
- close_gld volume_gld_day1
- low_spy_day1 high_spy_high_vol3d
- low_spy_day1 low_bnd_low_vol5d
- volume_ief_day1 close_spy_day20
- volume_bnd_day3 volume_ief_day20
- low_gld_day7 high_gld_day20
- low_gld_day20 month_first_day
- close_gld_day20 gdaxi_rsi
- open_gdaxi_kmomentum low_spy_low_vol3d
threshold: 0.43743743743743746
xgb_classifier_params:
  colsample_bytree: 0.8261516802102762
  gamma: 0.037610876072606714
  learning_rate: 0.00016588382096877736
  max_depth: 11
  min_child_weight: 6
  n_estimators: 986
  reg_alpha: 0.050572017262021866
  reg_lambda: 0.042334410117589455
  subsample: 0.5113067189362983
